---
title: "Lab file 4a"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(tidyverse)
```

```{r}
surveys_complete <- read_csv("data/surveys_complete.csv")

```

```{r}
ggplot(data = surveys_complete)
```

```{r}
ggplot(data = surveys_complete, mapping = aes(x = weight, y = hindfoot_length))
```

```{r}
ggplot(data = surveys_complete, aes(x = weight, y = hindfoot_length)) +
  geom_point()
```

```{r}
install.packages("hexbin")
library("hexbin")
```

```{r}
surveys_complete +
 geom_hex()
```

```{r}
ggplot(data = surveys_complete, aes(x = weight, y = hindfoot_length)) +
    geom_point()
```
```{r}
ggplot(data = surveys_complete, aes(x = weight, y = hindfoot_length)) +
    geom_point(alpha = 0.1)
```

```{r}
ggplot(data = surveys_complete, mapping = aes(x = weight, y = hindfoot_length)) +
    geom_point(alpha = 0.1, color = "blue")
```

```{r}
ggplot(data = surveys_complete, mapping = aes(x = weight, y = hindfoot_length)) +
    geom_point(alpha = 0.1, aes(color = species_id))
```
```{r}
ggplot(data = surveys_complete, 
       mapping = aes(x = species_id, y = weight)) +
   geom_point(aes(color = plot_type))
```
```{r}
ggplot(data = surveys_complete, mapping = aes(x = species_id, y = weight)) +
    geom_boxplot()
```
```{r}
ggplot(data = surveys_complete, mapping = aes(x = species_id, y = weight)) +
    geom_boxplot(alpha = 0) +
    geom_jitter(alpha = 0.3, color = "tomato")
```

