---
title: "Lab 4"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(tidyverse)
```

```{r}
report_03_11_2020 <-   read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-11-2020.csv")) %>%
  rename(Country_Region = "Country/Region", Province_State = "Province/State")
```
```{r}
str(report_03_11_2020)
```


```{r}
install.packages("DT")
```

```{r}
library(DT)
```
```{r}
datatable(report_03_11_2020)
```
## Excercises Part 1

## 1. 

```{r}
report_09_13_2020 <- read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/09-13-2020.csv")) 
 
```

```{r}
str(report_09_13_2020)
```



## 2. 

```{r}
report_09_13_2020 %>%   group_by(Country_Region) %>% summarize(Deaths = sum(Deaths, na.rm = TRUE))
```

## 3. 

```{r}
report_09_13_2020 %>%  filter(Country_Region == "US") %>% group_by(Province_State) %>% summarize(Deaths = sum(Deaths, na.rm = TRUE))
```

## 4.
```{r}
report_09_13_2020 %>%   group_by(Country_Region) %>% summarize(Deaths = sum(Deaths, na.rm = TRUE)) %>% arrange(desc(Deaths)) %>% slice_max(Deaths, n = (10))
```

## Excercise Part 2 

## 1. 

## 9_13_2020 data
```{r}
Top10Deaths <- report_09_13_2020 %>%   group_by(Country_Region) %>% summarize(Deaths = sum(Deaths, na.rm = TRUE)) %>% arrange(desc(Deaths)) %>% slice_max(Deaths, n = (10))
```
```{r}
ggplot(data = Top10Deaths, aes(x = Country_Region, y = Deaths)) +
  geom_point()
```


```{r}
report_09_13_2020 %>%   group_by(Country_Region) %>% summarize(Confirmed = sum(Confirmed, na.rm = TRUE)) %>% arrange(desc(Confirmed)) %>% slice_max(Confirmed, n = (10))
```

```{r}
Top10Confirmed <- report_09_13_2020 %>%   group_by(Country_Region) %>% summarize(Confirmed = sum(Confirmed, na.rm = TRUE)) %>% arrange(desc(Confirmed)) %>% slice_max(Confirmed, n = (10))
```

```{r}
ggplot(data = Top10Confirmed, aes(x = Country_Region, y = Confirmed)) +
  geom_point()
```

## 3_11_2020
```{r}
Top10Deaths3_11 <- report_03_11_2020 %>%   group_by(Country_Region) %>% summarize(Deaths = sum(Deaths, na.rm = TRUE)) %>% arrange(desc(Deaths)) %>% slice_max(Deaths, n = (10))
```

```{r}
ggplot(data = Top10Deaths3_11, aes(x = Country_Region, y = Deaths)) +
  geom_point()
```

```{r}
Top10Confirmed3_11 <- report_03_11_2020 %>%   group_by(Country_Region) %>% summarize(Confirmed = sum(Confirmed, na.rm = TRUE)) %>% arrange(desc(Confirmed)) %>% slice_max(Confirmed, n = (10))
```
```{r}
report_03_11_2020 %>%   group_by(Country_Region) %>% summarize(Confirmed = sum(Confirmed, na.rm = TRUE)) %>% arrange(desc(Confirmed)) %>% slice_max(Confirmed, n = (10))
```

```{r}
ggplot(data = Top10Confirmed3_11, aes(x = Country_Region, y = Confirmed)) +
  geom_point()
```

## Excercise 2 Part 2

## 09_13_20 data

```{r}
report_09_13_2020 %>%  filter(Country_Region == "US") %>% group_by(Province_State) %>% summarize(Deaths = sum(Deaths, na.rm = TRUE))
```


```{r}
Top10DeathsStates9_13 <- report_09_13_2020 %>%  filter(Country_Region == "US") %>% group_by(Province_State) %>% summarize(Deaths = sum(Deaths, na.rm = TRUE)) %>% arrange(desc(Deaths)) %>% slice_max(Deaths, n = (10))
```

```{r}
ggplot(data = Top10DeathsStates9_13, aes(x = Province_State,  y = Deaths)) + 
    geom_bar(stat = 'identity') 
```

```{r}
report_09_13_2020 %>%  filter(Country_Region == "US") %>% group_by(Province_State) %>% summarize(Confirmed = sum(Confirmed, na.rm = TRUE)) %>% arrange(desc(Confirmed)) %>% slice_max(Confirmed, n = (10))
```

```{r}
Top10ConfirmedStates9_13 <- report_09_13_2020 %>%  filter(Country_Region == "US") %>% group_by(Province_State) %>% summarize(Confirmed = sum(Confirmed, na.rm = TRUE)) %>% arrange(desc(Confirmed)) %>% slice_max(Confirmed, n = (10))
```

```{r}
ggplot(data = Top10ConfirmedStates9_13, aes(x = Province_State,  y = Confirmed)) + 
    geom_bar(stat = 'identity') 
```

## Top 10 Confirmed and Deaths 3_11_20

```{r}
report_03_11_2020 %>%  filter(Country_Region == "US") %>% group_by(Province_State) %>% summarize(Deaths = sum(Deaths, na.rm = TRUE)) %>% arrange(desc(Deaths)) %>% slice_max(Deaths, n = (5))
```

```{r}
Top10DeathsStates3_11 <- report_03_11_2020 %>%  filter(Country_Region == "US") %>% group_by(Province_State) %>% summarize(Deaths = sum(Deaths, na.rm = TRUE)) %>% arrange(desc(Deaths)) %>% slice_max(Deaths, n = (5))
```

```{r}
ggplot(data = Top10DeathsStates3_11, aes(x = Province_State,  y = Deaths)) + 
    geom_bar(stat = 'identity') 
```

```{r}
report_03_11_2020 %>%  filter(Country_Region == "US") %>% group_by(Province_State) %>% summarize(Confirmed = sum(Confirmed, na.rm = TRUE)) %>% arrange(desc(Confirmed)) %>% slice_max(Confirmed, n = (10))
```

```{r}
Top10ConfirmedStates3_11 <- report_03_11_2020 %>%  filter(Country_Region == "US") %>% group_by(Province_State) %>% summarize(Confirmed = sum(Confirmed, na.rm = TRUE)) %>% arrange(desc(Confirmed)) %>% slice_max(Confirmed, n = (10))
```

```{r}
ggplot(data = Top10ConfirmedStates3_11, aes(x = Province_State,  y = Confirmed)) + 
    geom_bar(stat = 'identity') 
```

